import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import {getPicAsync} from '../picComp/picCompApi'

enum status {
    IDLE = 'idle',
    LOADING = 'loading',
    FAILED = 'failed',
}

export interface picState {
  pic: string;
  status: status;
}

const initialState: picState = {
  pic: '',
  status: status.IDLE,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const picCompSlice = createSlice({
  name: 'pic',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getPicAsync.pending, (state) => {
        state.status = status.LOADING;
      })
      .addCase(getPicAsync.fulfilled, (state, action) => {
        state.status = status.IDLE;
        console.log(action.payload, 'payLoad');
        
        state.pic = action.payload;
      })
      .addCase(getPicAsync.rejected, (state) => {
        state.status = status.FAILED;
      });
  },
});

// export const { increment } = picCompSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectPic = (state: RootState) => state.picComp.pic;
export const selectPicStatus = (state: RootState) => state.picComp.status;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.


export default picCompSlice.reducer;
